const sampleMovies = [
  {
    title: "Dune: Part Two",
    synopsis: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: ["English", "Hindi", "Tamil"],
    duration: 166,
    rating: 8.8,
    votesCount: 34200,
    certificate: "UA 16+",
    format: ["2D", "IMAX 3D", "4DX", "ICE"],
    poster: {
      url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
      filename: "dune2_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80",
      filename: "dune2_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    cast: [
      { name: "Timothée Chalamet", role: "Paul Atreides", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80" },
      { name: "Zendaya", role: "Chani", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80" },
      { name: "Rebecca Ferguson", role: "Lady Jessica", photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80" },
      { name: "Austin Butler", role: "Feyd-Rautha", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Denis Villeneuve",
    isTrending: true,
  },
  {
    title: "Oppenheimer",
    synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II, exploring the profound moral, psychological, and global consequences of humanity's greatest discovery.",
    genre: ["Biography", "Drama", "History"],
    language: ["English", "Hindi"],
    duration: 180,
    rating: 8.9,
    votesCount: 48900,
    certificate: "A",
    format: ["2D", "IMAX 3D"],
    poster: {
      url: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=600&q=80",
      filename: "oppenheimer_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
      filename: "oppenheimer_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    cast: [
      { name: "Cillian Murphy", role: "J. Robert Oppenheimer", photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80" },
      { name: "Emily Blunt", role: "Katherine Oppenheimer", photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80" },
      { name: "Matt Damon", role: "Leslie Groves", photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80" },
      { name: "Robert Downey Jr.", role: "Lewis Strauss", photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Christopher Nolan",
    isTrending: true,
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    synopsis: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
    genre: ["Animation", "Action", "Adventure", "Sci-Fi"],
    language: ["English", "Hindi", "Tamil", "Telugu"],
    duration: 140,
    rating: 8.7,
    votesCount: 29500,
    certificate: "U",
    format: ["2D", "3D", "4DX"],
    poster: {
      url: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80",
      filename: "spiderman_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=80",
      filename: "spiderman_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/cqGjhVJWtEg",
    cast: [
      { name: "Shameik Moore", role: "Miles Morales (voice)", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80" },
      { name: "Hailee Steinfeld", role: "Gwen Stacy (voice)", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80" },
      { name: "Oscar Isaac", role: "Miguel O'Hara (voice)", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Joaquim Dos Santos",
    isTrending: true,
  },
  {
    title: "Interstellar",
    synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans across a mysterious wormhole near Saturn.",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    language: ["English", "Hindi"],
    duration: 169,
    rating: 8.9,
    votesCount: 65100,
    certificate: "UA",
    format: ["2D", "IMAX 3D"],
    poster: {
      url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80",
      filename: "interstellar_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
      filename: "interstellar_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper", photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80" },
      { name: "Anne Hathaway", role: "Brand", photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80" },
      { name: "Jessica Chastain", role: "Murph", photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Christopher Nolan",
    isTrending: true,
  },
  {
    title: "Jawan",
    synopsis: "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society, alongside a fearless prison warden whose mission intertwines with national conspiracies.",
    genre: ["Action", "Thriller", "Drama"],
    language: ["Hindi", "Tamil", "Telugu"],
    duration: 169,
    rating: 8.2,
    votesCount: 42100,
    certificate: "UA 16+",
    format: ["2D", "4DX", "IMAX 3D"],
    poster: {
      url: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
      filename: "jawan_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=80",
      filename: "jawan_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/MWOlnZSnXWY",
    cast: [
      { name: "Shah Rukh Khan", role: "Vikram Rathore / Azad", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80" },
      { name: "Nayanthara", role: "Narmada Rai", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80" },
      { name: "Vijay Sethupathi", role: "Kalee Gaikwad", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Atlee",
    isTrending: false,
  },
  {
    title: "Fighter",
    synopsis: "Top IAF aviators come together in the face of imminent danger to form an elite unit named Air Dragons, navigating personal demons and aerial skirmishes to protect the sovereignty of the nation.",
    genre: ["Action", "Thriller"],
    language: ["Hindi", "Telugu"],
    duration: 166,
    rating: 7.9,
    votesCount: 18400,
    certificate: "UA",
    format: ["2D", "3D", "4DX"],
    poster: {
      url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
      filename: "fighter_poster",
    },
    backdrop: {
      url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=80",
      filename: "fighter_backdrop",
    },
    trailerUrl: "https://www.youtube.com/embed/9msG_u2r5q8",
    cast: [
      { name: "Hrithik Roshan", role: "Shamsher Pathania (Patty)", photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80" },
      { name: "Deepika Padukone", role: "Minal Rathore (Minni)", photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80" },
      { name: "Anil Kapoor", role: "Rakesh Jaisingh (Rocky)", photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80" },
    ],
    director: "Siddharth Anand",
    isTrending: false,
  },
];

const sampleTheatres = [
  {
    name: "PVR: INOX Megaplex, Phoenix Palladium",
    chain: "PVR",
    city: "Mumbai",
    address: "462, Senapati Bapat Marg, Lower Parel, Mumbai",
    location: { type: "Point", coordinates: [72.8258, 18.9986] },
    amenities: ["IMAX Laser", "Dolby Atmos 7.1", "Recliner Seats", "Gourmet F&B", "Wheelchair Accessible"],
    cancellationAvailable: true,
  },
  {
    name: "Cinepolis: Viviana Mall",
    chain: "Cinepolis",
    city: "Mumbai",
    address: "Eastern Express Highway, Near Jupiter Hospital, Thane, Mumbai",
    location: { type: "Point", coordinates: [72.9734, 19.2084] },
    amenities: ["4DX", "Dolby Atmos", "Recliner Seats", "VIP Lounge"],
    cancellationAvailable: true,
  },
  {
    name: "PVR: Director's Cut, Ambience Mall",
    chain: "PVR",
    city: "Delhi-NCR",
    address: "Ambience Mall, NH 8, Gurugram, Delhi-NCR",
    location: { type: "Point", coordinates: [77.097, 28.504] },
    amenities: ["IMAX Laser", "Luxury Dine-in", "Ultra Recliner", "Valet Parking"],
    cancellationAvailable: true,
  },
  {
    name: "INOX: Insignia, Epicuria",
    chain: "INOX",
    city: "Delhi-NCR",
    address: "Nehru Place Metro Station, Epicuria, New Delhi",
    location: { type: "Point", coordinates: [77.2514, 28.551] },
    amenities: ["Dolby 7.1", "Gourmet Concessions", "Recliners"],
    cancellationAvailable: true,
  },
  {
    name: "PVR: Forum Mall, Koramangala",
    chain: "PVR",
    city: "Bengaluru",
    address: "Hosur Road, Chikku Lakshmaiah Layout, Koramangala, Bengaluru",
    location: { type: "Point", coordinates: [77.6111, 12.9345] },
    amenities: ["IMAX 3D", "Dolby Atmos", "Food Court"],
    cancellationAvailable: true,
  },
  {
    name: "Cinepolis: Forum Sujana Mall",
    chain: "Cinepolis",
    city: "Hyderabad",
    address: "Kukatpally Housing Board Colony, Hyderabad",
    location: { type: "Point", coordinates: [78.3871, 17.4852] },
    amenities: ["Dolby Atmos", "Recliner", "4DX"],
    cancellationAvailable: true,
  },
];

module.exports = {
  sampleMovies,
  sampleTheatres,
};
